import { Sidebar } from "@/components/sidebar";
import { Button } from "@/components/ui/button";
import { ThemeProvider } from "@/context/theme";
import { UserContextProvider } from "@/context/user";
import type { Metadata } from "next";

import Link from "next/link";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <UserContextProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="grid grid-cols-12">
              <div className="col-span-3">
                <Sidebar />
              </div>
              <div className="col-span-9 p-6 w-full">
                <div className="flex justify-between border-b items-center">
                  <h1 className="text-4xl py-4">Dashboard</h1>
                  <div className="space-x-4">
                    <Button variant="default" className="rounded-sm">
                      <Link href="/login">Portfolio</Link>
                    </Button>
                    <Button variant="secondary" className="rounded-sm">
                      <Link href="/login">History</Link>
                    </Button>
                    <Button variant="secondary" className="rounded-sm">
                      <Link href="/login">Analytics</Link>
                    </Button>
                  </div>
                </div>
                {children}
              </div>
            </div>
          </ThemeProvider>
        </UserContextProvider>
      </body>
    </html>
  );
}
